spring:
  datasource:
    url: jdbc:h2:mem:blog
    username: h2
    password: root
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  error:
    include-stacktrace: never